USE WeVote;
SELECT *
FROM [we vote - MASTER CANDIDATE and VOTE TABLE - final];
SELECT *
FROM [we vote - MASTER COMMUNITIES TABLE ISSUES REPORT - final];
SELECT *
FROM [we vote - MASTER COMMUNITIES TABLE ISSUES REPORT - final]
WHERE CommunityIDs is NOT NULL;
SELECT *
FROM [we vote - MASTER COMMUNITIES TABLE ISSUES REPORT - final]
WHERE CommunityIDs is NULL;
